padre(hilario).
padre(atanacio).
padre(javier).
padre(hector).
padre(martin).
padre(alfredo).
padre(jesus).
padre(erasmo).
padre(tomas).
padre(francisco).
padre(roberto).
padre(juan).
padre(ricardo).
madre(cirina).
madre(elena).
madre(leticia).
madre(olga).
madre(hilda).
madre(estela).
madre(maria).
madre(lidia).
madre(lupe).
madre(josefina).

padrede(javier,josue).